[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[functions."sync-strava-scheduled"]
  schedule = "0 13 * * *"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
